services:
  app:
    container_name: prospero-frontend
    image: ghcr.io/prospero-inc/prospero-front:latest
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - '4000:3000'
    networks:
      - prospero
networks:
  prospero:
    external: true
