services:
  app:
    image: prospero-app
    env_file:
      - .env.production
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - NEXT_PUBLIC_API_URL
        - NEXT_PUBLIC_API_KEY
        - NEXT_AUTH_SECRET
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - '4000:3000'
