name: Delete Branch

on:
  pull_request:
    types: 
      - closed
jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Delete branch
      env:
        GITHUB_TOKEN: ${{ secrets.PROSPERO_SECRET }}
      run: |
        BRANCH_NAME=$(echo "${{ github.head_ref }}" | sed 's/refs\/heads\///')
        echo "Deleting branch: $BRANCH_NAME"
        curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
             "https://api.github.com/repos/${{ github.event.ref }}/git/refs/heads/$BRANCH_NAME"
