name: Deploy Prospero Frontend

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: self-hosted

    env:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Lint
        run: pnpm lint

      - name: Stop existing container
        run: |
          docker compose down
          docker image prune

      - name: Deploy Docker container
        run: |
          docker compose up --build -d
