name: Deploy Prospero Frontend

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Docker container
        run: |
          docker compose up

      - name: Stop existing container
        run: |
          docker compose down
